spring.application.name=server

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/plant_pals
spring.datasource.username=plant_pals_user
spring.datasource.password=password

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
